#! /bin/bash

mkdir -p libs
cd libs

tar xzf ../archives/arpack96.tar.gz
tar xzf ../archives/parpack96.tar.gz
tar xzf ../archives/patch.tar.gz
tar xzf ../archives/ppatch.tar.gz
cd ARPACK
cp ARMAKES/ARmake.MPI-SP2 ARmake.inc
rm PARPACK/SRC/MPI/mpif.h
rm PARPACK/UTIL/MPI/mpif.h
rm PARPACK/EXAMPLES/MPI/mpif.h

../../subs.py ../../arpackpatches/patch1.template `pwd` | patch -p0
patch -p0 < ../../arpackpatches/patch2
patch -p0 < ../../arpackpatches/patch3

make -j2 all

ln -s libarpack_SP2.a libarpack.a
ln -s parpack_MPI-SP2.a libparpack.a
